# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 19:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=24, verbose_name='菜单名称')),
                ('icon', models.CharField(blank=True, max_length=24, null=True)),
                ('weight', models.PositiveIntegerField(default=50, verbose_name='菜单权重')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '角色控制',
                'verbose_name_plural': '角色控制',
            },
        ),
        migrations.CreateModel(
            name='Userpurview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=80)),
                ('show', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=24, verbose_name='路由别名')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', unique=True, verbose_name='所属菜单')),
            ],
            options={
                'verbose_name': '权限控制',
                'verbose_name_plural': '权限控制',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='rbac.Userpurview'),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(related_name='roles', to=settings.AUTH_USER_MODEL),
        ),
    ]
