# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181128_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurview',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='所属菜单'),
        ),
        migrations.AlterField(
            model_name='userpurview',
            name='name',
            field=models.CharField(max_length=24, verbose_name='路由别名'),
        ),
    ]
