# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20190113_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpurview',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='所属菜单'),
        ),
    ]
